// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADoq6rcObz0uCkYirz1C0J5ak_jgSaLxc',
    appId: '1:889819067380:android:3da31e47005ca88966bfa1',
    messagingSenderId: '889819067380',
    projectId: 'sparfuchs-ai-v1',
    storageBucket: 'sparfuchs-ai-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADoq6rcObz0uCkYirz1C0J5ak_jgSaLxc',
    appId: '1:889819067380:ios:fb94e1b5787a796966bfa1',
    messagingSenderId: '889819067380',
    projectId: 'sparfuchs-ai-v1',
    storageBucket: 'sparfuchs-ai-v1.firebasestorage.app',
    iosBundleId: 'de.sparfuchs.sparfuchsAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADoq6rcObz0uCkYirz1C0J5ak_jgSaLxc',
    appId: '1:889819067380:ios:b343f2fd9e55a9de66bfa1',
    messagingSenderId: '889819067380',
    projectId: 'sparfuchs-ai-v1',
    storageBucket: 'sparfuchs-ai-v1.firebasestorage.app',
    iosBundleId: 'de.sparfuchs.sparfuchs_ai', // Using the ID I supplied to CLI
  );
}
